PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX base:        <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX operational:        <http://opencaesar.io/example/vocabulary/operational#>

#SELECT DISTINCT ?iri ?id ?name ?type
SELECT DISTINCT ?p_name ?c_name
WHERE {
	?iri a operational:RoadVehicle ;
		base:hasCanonicalName ?p_name ;
  		base:aggregates ?childiri .
#  		base:isAggregatedIn ?childiri .  
  OPTIONAL{
    	?childiri base:hasCanonicalName ?c_name;
               }
}
ORDER BY ?iri